name: Update Blocklist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 UTC

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download blocklist
        run: |
          curl -sSL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.mini-onlydomains.txt -o blocklist.txt

      - name: Remove first 11 lines
        run: |
          tail -n +12 blocklist.txt > pro.mini-onlydomains.txt

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add pro.mini-onlydomains.txt
          git commit -m "Update processed blocklist"
          git push

  dispatch-auto:
    needs: [update-blocklist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        # required
        app-id: ${{ vars.TERRAFORM_APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        permission-actions: write
        repositories: |
          miljodir/${{ vars.TERRAFORM_REPO_NAME }}
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: blocklist-updated
        token: ${{ steps.app-token.outputs.token }}
        repository: miljodir/${{ vars.TERRAFORM_REPO_NAME }}
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'